env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  '@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
  'no-constant-condition': ['error', { 'checkLoops': false }],
  'no-empty': ['error', { 'allowEmptyCatch': true }]
}
